apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An open source framework for building developer portals
  annotations:
    argocd/app-selector: "component=backstage"
    github.com/project-slug: dsoderlund-consulting/demo-backstage
  tags:
    - typescript
    - postgres
    - redis
  links:
    - url: https://backstage.io/
      title: Backstage website
      icon: docs
    - url: https://github.com/backstage/backstage
      title: Source code
      icon: github
spec:
  type: service
  owner: dsoderlund.consulting
  system: ds-ref-platform
  lifecycle: production
