load('ext://git_resource', 'git_checkout')
load('ext://deployment', 'deployment_create')
load('ext://configmap', 'configmap_create')

# Deploy CNPG
git_checkout('https://github.com/dsoderlund-consulting/demo-platform.git#main', './demo-platform')
k8s_yaml('demo-platform/cnpg-install.yaml')

# Database
k8s_yaml('cnpg/postgres-cluster.yaml')
k8s_resource(
  resource_deps=['cnpg-controller-manager'],
  new_name='database',
  objects=['backstage-postgres-cluster'],
  extra_pod_selectors=[{'cnpg.io/cluster': 'backstage-postgres-cluster'}],
  port_forwards=5432)

# Backstage
configmap_create(
  'backstage-config',
  from_env_file=".env.yarn",
  from_file="app-config.production.yaml"
)
docker_build(".", "demo-backstage")
deployment_create(
  'backstage',
  ports='7007',

  envFrom=[{
    "secretRef":{
      "name": "backstage-postgres-cluster-app" # autogenerated when creating a postgres cluster without any initdb arguments
    }
  }]
  )
k8s_resource(
  workload='backstage',
  port_forwards=7007,
  resource_deps=['database']
)

