apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: gittester-template
  title: gittester
  description: git tester
spec:
  owner: group:dsoderlund.consulting
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - repoName
        - repoConfiguration
      properties:
        repoName:
          title: repoName
          type: string
          description: Repo Name
          ui:autofocus: true
        repoConfiguration:
          title: repoConfiguration
          type: string
          description: Repo Configuration
          default: nas

  steps:
    - id: gitops-clone
      name: Clone Gitops Repo
      action: git:clone
      input:
        repoName: ${{ parameters.repoName }}
        repoConfiguration: ${{ parameters.repoConfiguration }}

  output:
    text:
      - title: debug information
        content: |
          ** Number of files: `${{ steps['gitops-clone'].output.files }}`