apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{ values.component }}-frontend"
  links:
    - url: https://${{ values.component }}.sam.dsoderlund.consulting
      title: CI/CD Deployment
      icon: website
spec:
  type: website
  owner: ${{ values.team }}
  lifecycle: experimental
  subcomponentOf: ${{ values.component | dump }}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{ values.component }}-backend"
  links:
    - url: https://${{ values.component }}.sam.dsoderlund.consulting/api
      title: CI/CD Deployment
      icon: service
spec:
  type: service
  owner: ${{ values.team }}
  lifecycle: experimental
  subcomponentOf: ${{ values.component | dump }}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    argocd/app-selector: "component=${{ values.component }}"
    github.com/project-slug: dsoderlund-consulting/${{ values.component }}
  links:
    - url: https://${{ values.component }}.sam.dsoderlund.consulting
      title: CI/CD Deployment (frontend)
      icon: website
    - url: https://${{ values.component }}.sam.dsoderlund.consulting/api
      title: CI/CD Deployment (backend)
      icon: service
spec:
  type: service
  owner: ${{ values.team }}
  lifecycle: experimental
  system: ${{ values.system }}
