apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{ values.component }}-frontend"
spec:
  type: website
  owner: ${{ values.team }}
  lifecycle: experimental
  subcomponentOf: ${{ values.component | dump }}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{ values.component }}-backend"
spec:
  type: service
  owner: ${{ values.team }}
  lifecycle: experimental
  subcomponentOf: ${{ values.component | dump }}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    argocd/app-selector: "component=${{ values.component }}"
spec:
  type: service
  owner: ${{ values.team }}
  lifecycle: experimental
  system: ${{ values.system }}
