apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${{ values.component }}-postgres-cluster
  namespace: default
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  postgresql:
    parameters:
      shared_buffers: 128MB


