apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: ${{ values.component | dump }}
spec:
  ingress:
    hostname: ${{ values.component }}.sam.dsoderlund.consulting
  database:
    replicas: 1