apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-ds-templates
  description: All templates from this repo
spec:
  targets:
    - ./example-nodejs-template/template.yaml
    - ./mssql-cicd/template.yaml
    - ./demo-fullstack-template/template.yaml
    - ./gittester/template.yaml
    